name: Issue Close Question

on:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  issue-close-require:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: needs more info
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issues'
          labels: 'question'
          inactive-day: 3
          body: |
            This issue has been closed automatically because it has not had recent activity for 3 days. If you have any questions, please comment here.
            由于该 Issue 3天未收到回应，现已被自动关闭，若有任何问题，可评论回复。

